import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./reset.css";
import Header from "./components/Header";

const sourceCodePro = Source_Code_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourceCodePro.className}>
        <Header />

        {children}
      </body>
    </html>
  );
}
